language: python
python:
  - "3.4"
  - "pypy"
# command to install dependencies
install:
  - pip install https://github.com/dcramer/pyflakes/tarball/master
  - pip install -q -e . --use-mirrors
 # command to run tests
  script:
  - python app.py test