language: python
python:
  - "3.4"
  # does not have headers provided, please ask https://launchpad.net/~pypy/+archive/ppa
  # maintainers to fix their pypy-dev package.
  - "pypy"
# command to install dependencies
install:
  - pip install -q -e . --use-mirrors
 # command to run tests
  script:
  - python app.py test